# Generated by Django 5.2 on 2025-04-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personId', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('lastPlayed', models.CharField(max_length=15)),
                ('rating', models.IntegerField(default=5)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
